pyccel/psydac

examples/poisson_2d_mapping.py, examples/test_mass_matrix.py, examples/visualize_matrices.py, spl/linalg/block.py, spl/mapping/discrete.py, spl/polar/c1_linops.py, spl/polar/c1_projections.py, spl/polar/dense.py, spl/polar/tests/test_c1_projections.py
Enforce continuity of gradient of solution field across polar singularity of mapping (O-point).
=> Devel polar

spl/api/codegen/ast.py
a new implementation of computing logical expressions, that works for any derivative order. Some improvements will be done in the future to enhance the performance, in sympde.
=> Devel mapping

performance/test_perf_2d.py, performance/test_perf_2d_parallel.py, performance/test_perf_3d.py, spl/api/codegen/ast.py, spl/api/discretization.py, spl/api/tests/test_api_2d_scalar.py, spl/api/tests/test_api_2d_scalar_mapping.py, spl/api/tests/test_api_2d_system.py, spl/api/tests/test_api_2d_vector.py, spl/api/tests/test_api_2d_vector_mapping.py, spl/api/tests/test_api_3d_scalar.py, spl/api/tests/test_api_3d_scalar_mapping.py, spl/api/tests/test_api_3d_vector.py, spl/api/tests/test_api_3d_vector_mapping.py
- use last version of sympde: improving expressions and cleaner code
- change declaration of Field to match other constructors: TestFunction, VectorField, VectorTestFunction
=> Devel expr

spl/api/codegen/ast.py, spl/api/codegen/printing.py
remove pyccel/textx dependencies from sympde
=> [api] move pycode from sympde to spl

spl/api/tests/test_api_2d_scalar.py, spl/api/tests/test_api_2d_scalar_mapping.py, spl/api/tests/test_api_2d_system.py, spl/api/tests/test_api_2d_vector.py, spl/api/tests/test_api_2d_vector_mapping.py, spl/api/tests/test_api_3d_scalar.py, spl/api/tests/test_api_3d_scalar_mapping.py, spl/api/tests/test_api_3d_vector.py, spl/api/tests/test_api_3d_vector_mapping.py
add user friendly function to create equations, works for linear systems and newton iteration
=> [api] use find function to create symbolic equations

spl/api/tests/test_api_2d_scalar.py, spl/api/tests/test_api_2d_scalar_mapping.py, spl/api/tests/test_api_2d_system.py, spl/api/tests/test_api_2d_vector.py, spl/api/tests/test_api_2d_vector_mapping.py, spl/api/tests/test_api_3d_scalar.py, spl/api/tests/test_api_3d_scalar_mapping.py, spl/api/tests/test_api_3d_vector.py, spl/api/tests/test_api_3d_vector_mapping.py, spl/fem/vector.py
Simplify creation of FemField objects in all API tests, which are useful examples for the user.
=> Devel field

spl/ddm/cart.py
the __del__ method is automatically handled by python and mpi4py
=> delet the del method in CartDecomposition

performance/test_perf_1d.py, performance/test_perf_2d.py, performance/test_perf_2d_parallel.py, performance/test_perf_3d.py, psydac/api/ast/evaluation.py, psydac/api/ast/fem.py, psydac/api/discretization.py, psydac/api/fem.py, psydac/api/tests/test_api_1d_compatible_spaces.py, psydac/api/tests/test_api_2d_compatible_spaces.py, psydac/api/tests/test_api_2d_scalar.py, psydac/api/tests/test_api_2d_scalar_mapping.py, psydac/api/tests/test_api_2d_system.py, psydac/api/tests/test_api_2d_vector.py, psydac/api/tests/test_api_2d_vector_mapping.py, psydac/api/tests/test_api_3d_scalar.py, psydac/api/tests/test_api_3d_scalar_mapping.py, psydac/api/tests/test_api_3d_vector.py, psydac/api/tests/test_api_3d_vector_mapping.py, psydac/api/tests/test_api_expr_2d_scalar.py, psydac/api/tests/test_api_feec_2d.py, psydac/api/tests/test_api_glt_2d_scalar.py, psydac/api/tests/test_api_glt_2d_scalar_mapping.py, psydac/api/tests/test_api_glt_2d_vector.py
=> Change API: FunctionSpace -> ScalarFunctionSpace, element_of_space -> element_of

psydac/api/ast/evaluation.py, psydac/api/ast/expr.py, psydac/api/ast/fem.py, psydac/api/ast/glt.py, psydac/api/ast/utilities.py, psydac/api/expr.py, psydac/api/printing/pycode.py, psydac/api/tests/test_api_1d_compatible_spaces.py, psydac/api/tests/test_api_2d_scalar_mapping.py, psydac/api/tests/test_api_expr_2d_scalar.py
=> Use SymbolicExpr instead of print_expression and pycode.

psydac/api/ast/fem.py, psydac/api/ast/nodes.py, psydac/api/ast/parser.py, psydac/api/ast/tests/poisson.py, psydac/api/basic.py, psydac/api/discretization.py, psydac/api/fem.py, psydac/api/tests/test_api_2d_scalar_mapping.py
=> Revert "Psydac ast"

psydac/api/ast/nodes.py, psydac/api/ast/utilities.py
Delete unused function `physical2logical`
=> Delete unused function physical2logical

psydac/feec/pull_push.py
H1 'push-forward' added, for consistency
=> Add H1 push-forwards for consistency

psydac/api/discretization.py, psydac/api/essential_bc.py, psydac/api/tests/test_api_feec_1d.py
A single low-level function, `apply_essential_bc_stencil`, works for multiple classes in any number of dimensions:
- `StencilVector`
- `StencilMatrix`
- `StencilInterfaceMatrix`
The high-level function `apply_essential_bc`, which dispatches the work to low-level functions, does not require the space `V` as an argument any more.
=> Cleanup and simplify application of essential BCs

psydac/cad/tests/test_geometry.py, psydac/fem/basic.py, psydac/fem/splines.py, psydac/fem/tensor.py, psydac/mapping/discrete.py
- Improve `eval_field` to compute weighted fields
- Add tests for the evaluation of `NurbsMapping`
=> Fix evaluation of non-uniform rational B-splines (NURBS)

psydac/api/fem.py, psydac/api/grid.py, psydac/core/bsplines.py, psydac/core/kernels.py, psydac/fem/tensor.py, psydac/fem/vector.py, psydac/mapping/discrete.py, psydac/mapping/tests/test_discrete_mapping.py, psydac/utilities/utils.py
=> Improve `FemField` evaluation and small fixes

psydac/core/bsplines.py, psydac/fem/vector.py
This PR fixes `VectorFemSpace.eval_fields`which previously did not check if the `weights` argument existed. 
This fix consists of:
* Adding `if weights is not None` check.
=> Fix `VectorFemField.eval_field`

psydac/core/tests/test_kernels.py, psydac/fem/basic.py, psydac/fem/tensor.py, psydac/mapping/discrete.py, psydac/mapping/tests/test_discrete_mapping.py, setup.py
This PR simply adds pointwise evaluation of the Jacobian related quantities for the `NurbsMapping` class. 
`psydac/core/tests/test_kernels.py` doesn't pass because of an error is the kernel functions that has been fixed in #214
=> Add Jacobian matrix pointwise evaluation to `NurbsMapping`

psydac/linalg/stencil.py
=> Free MPI channels when StencilVector is deleted

psydac/linalg/stencil.py
=> Remove duplicated call to _dot in scalar product

psydac/feec/pull_push.py
Fix #178 : Each push-forward functions now compute the field only once
=> Push-forward function optimization

README.md
Provide Homebrew command to find HDF5 library path on macOS.
=> Update README.md with installation path info for hdf5-mpi 

psydac/api/fem.py, psydac/api/tests/build_domain.py, psydac/api/tests/test_2d_multipatch_mapping_maxwell.py, psydac/api/tests/test_2d_multipatch_mapping_poisson.py, psydac/api/tests/test_2d_multipatch_poisson.py, psydac/api/tests/test_postprocessing.py, psydac/cad/multipatch.py, psydac/feec/multipatch/multipatch_domain_utilities.py, pyproject.toml
Use SymPDE version 0.17.0. See SymPDE PR #130.
=> Use the new Domain.join() constructor of SymPDE

.github/workflows/continuous-integration.yml
=> Test Pyccel optimization flags in CI
