pyccel/psydac

.travis.yml
psydac/cad/tests/test_geometry.py
pytest.ini
requirements.txt
setup.py

Since Psydac was built using the latest versions of **pyccel** and **sympde** available on PyPI, unit tests on our default branch `devel` started failing after some breaking changes in both libraries. Starting with this pull request we are going to build Psydac using specific versions of those libraries.

Fix installation requirements to successfully run all unit tests

---

.travis.yml
psydac/api/ast/fem.py
psydac/api/ast/parser.py
psydac/api/basic.py
psydac/api/printing/pycode.py
psydac/api/tests/test_api_2d_scalar_backends.py
setup.py

Psydac now can use Pyccel and Numba to accelerate its pure Python kernels. In addition:
- Drop Python-3.5 support, because Numba does not support it
- Add Python-3.8
- Add parallel tests

Add Pyccel and Numba backends

---

.gitignore
psydac/api/tests/test_api_2d_scalar.py
psydac/api/tests/test_api_2d_scalar_analytical_mapping.py
psydac/api/tests/test_api_2d_scalar_backends.py
psydac/api/tests/test_api_2d_scalar_mapping.py
psydac/api/tests/test_api_2d_scalar_mapping_multi_patch.py
psydac/api/tests/test_api_2d_scalar_multi_patch.py
psydac/api/tests/test_api_2d_system.py
psydac/api/tests/test_api_2d_vector.py
psydac/api/tests/test_api_2d_vector_mapping.py
psydac/api/tests/test_api_3d_scalar.py
psydac/api/tests/test_api_3d_scalar_mapping.py
psydac/api/tests/test_api_3d_vector.py
psydac/api/tests/test_api_3d_vector_mapping.py
psydac/api/tests/test_api_feec_3d.py
psydac/api/tests/test_api_glt_2d_scalar.py
psydac/api/tests/test_api_glt_2d_scalar_mapping.py
psydac/api/tests/test_api_glt_2d_vector.py

in order to work with Sympy version 1.7 or newer, we must now write explicitly `from sympy.core import cache`, because `from sympy import cache` does not work anymore. This closes #82.

Import cache from sympy.core

---

psydac/api/ast/expr.py
psydac/api/ast/fem.py
psydac/api/ast/glt.py
psydac/api/ast/parser.py
psydac/api/ast/utilities.py
psydac/api/discretization.py
psydac/api/fem.py
psydac/api/glt.py
psydac/api/grid.py
psydac/api/tests/test_api_2d_fields.py
psydac/api/tests/test_api_glt_2d_scalar.py
setup.py

- Fix evaluation of discrete fields in assembly of linear and bilinear forms;
- Delete `BoundaryQuadratureGrid` class and use `QuadratureGrid` for all cases;
- Add non linear Poisson example and other unit tests;
- Use Sympy version 0.10.7.

Fix field evaluation in linear and bilinear forms

---

psydac/api/ast/parser.py
psydac/api/essential_bc.py
psydac/api/fem.py
psydac/api/grid.py
psydac/api/tests/test_api_feec_1d.py
psydac/api/tests/test_api_feec_2d.py
psydac/feec/derivatives.py
psydac/feec/global_projectors.py
psydac/feec/pull_push.py
psydac/feec/tests/test_global_projectors.py
psydac/linalg/basic.py
psydac/linalg/block.py
psydac/linalg/iterative_solvers.py
psydac/linalg/kron.py
psydac/linalg/stencil.py
psydac/polar/c1_linops.py
psydac/polar/dense.py
setup.py

Apply homogeneous Dirichlet boundary conditions to V0 space of de Rham sequence. This PR also fixes #80.
**New features**
- Add option to 1D Maxwell test: Dirichlet BCs can be applied by penalizing the mass-matrix bilinear form, or strongly;
- Add 2D Maxwell test, where Dirichlet BCs are applied by penalizing the mass-matrix bilinear form;
- Add magic methods to `Matrix` and `Vector` base classes;
- Make Jacobi preconditioner work on block matrices, and for any number of dimensions;
- Change behavior of `BlockLinearOperator` for single row or column:
- If no. of rows == 1, codomain does not have to be `ProductSpace`;
- If no. of columns == 1 domain does not have to be `ProductSpace`;
- Accordingly, dot product allows non-block vectors as input or output;
- Further, `ProductSpace` …

FEEC with Dirichlet BCs.

---

psydac/api/fem.py
psydac/api/tests/test_api_2d_vector_mapping.py
psydac/api/tests/test_api_3d_scalar_mapping.py
psydac/api/tests/test_api_3d_vector.py
psydac/api/tests/test_api_glt_2d_scalar.py
psydac/feec/derivatives.py
psydac/fem/vector.py
psydac/linalg/block.py
psydac/linalg/tests/test_block.py
psydac/linalg/utilities.py
psydac/polar/c1_projections.py
psydac/polar/c1_spaces.py
psydac/polar/tests/test_c1_linops.py

Fixes #92. Class `ProductSpace` from module `psydac.linalg.block` caused a name clash with class `ProductSpace` from module `sympde.topology.space`. Therefore we have renamed it as `BlockVectorSpace`, which is consistent with the other names in the same module.

Rename ProductSpace as BlockVectorSpace

---

psydac/api/ast/evaluation.py
psydac/api/ast/expr.py
psydac/api/ast/fem.py
psydac/api/ast/glt.py
psydac/api/ast/nodes.py
psydac/api/ast/utilities.py
psydac/api/discretization.py
setup.py

Use SymPDE version 0.11. Accordingly, rename imported classes:
- `ScalarTestFunction` -> `ScalarFunction`,
- `VectorTestFunction` -> `VectorFunction`,
- `IndexedTestTrial` -> `IndexedVectorFunction`.
See also SymPDE's pull request [no. 97](https://github.com/pyccel/sympde/pull/97).

Use new names for SymPDE classes

---

psydac/api/fem.py
psydac/api/tests/test_api_2d_compatible_spaces.py
psydac/api/tests/test_api_2d_scalar_analytical_mapping.py
psydac/api/tests/test_api_2d_scalar_mapping_multi_patch.py
psydac/api/tests/test_api_2d_scalar_multi_patch.py
psydac/api/tests/test_api_2d_system.py
psydac/api/tests/test_api_2d_vector.py
psydac/api/tests/test_api_2d_vector_mapping.py
psydac/api/tests/test_api_3d_vector.py
psydac/api/tests/test_api_3d_vector_mapping.py
psydac/api/tests/test_api_expr_2d_scalar.py
psydac/api/tests/test_api_feec_3d.py
psydac/feec/derivatives.py
psydac/feec/global_projectors.py
psydac/feec/tests/test_differentiation_matrices.py
psydac/feec/tests/test_global_projectors.py
psydac/fem/basic.py
psydac/fem/splines.py
psydac/fem/tensor.py
psydac/fem/tests/test_product.py
psydac/fem/vector.py

- Add abstract property `is_product` to base class `FemSpace`;
- Add property `fields` and magic method `__getitem__` to  `FemField`;
- Allow `FemField` to represent any kind of field (scalar, vector, "product", etc.);
- Add basic linear operations (add, subtract, scalar multiply) to `FemField` objects;
- Remove obsolete class `VectorFemField`, which is only a source of confusion at this point.

Improve FemField and remove VectorFemField

---

psydac/api/discretization.py
psydac/api/tests/test_api_2d_fields.py
psydac/api/tests/test_api_2d_scalar.py
psydac/api/tests/test_api_2d_scalar_analytical_mapping.py
psydac/api/tests/test_api_2d_scalar_backends.py
psydac/api/tests/test_api_2d_scalar_mapping.py
psydac/api/tests/test_api_2d_scalar_mapping_multi_patch.py
psydac/api/tests/test_api_2d_scalar_multi_patch.py
psydac/api/tests/test_api_2d_system.py
psydac/api/tests/test_api_2d_vector.py
psydac/api/tests/test_api_2d_vector_mapping.py
psydac/api/tests/test_api_3d_scalar.py
psydac/api/tests/test_api_3d_scalar_mapping.py
psydac/api/tests/test_api_3d_vector.py
psydac/api/tests/test_api_3d_vector_mapping.py

Now the method `solve` of class `DiscreteEquation` from module `psydac.api.discretization` returns a `FemField` object instead of a `Vector` of coefficients.

Make DiscreteEquation.solve() return a FemField

---

psydac/api/essential_bc.py

- Fix bug in `apply_essential_bc_{2|3}d_StencilMatrix` when `domain != codomain`;
- Add consistency checks to the same functions;
- Clean up functions`apply_essential_bc_{1|2|3}d_StencilVector` for consistency.

Fix bug in application of essential boundary conditions to linear systems

---

.github/workflows/continuous-integration.yml

On 9 March 2021 GitHub Actions changed the value of `ubuntu-latest` from `ubuntu-18.04` to `ubuntu-20.04`. As a result all of our builds failed because of installation problems for both `mpi4py` and `h5py`. This PR addresses this problem and cleans up our configuration:
- Use "apt-get update" before installing packages;
- Run tests with Python 3.6 and 3.7 on Ubuntu 18.04;
- Run tests with Python 3.8 on Ubuntu 20.04;
- Use separate pip cache files based on operating system and Python version;
- Customize jobs names based on operating system and Python version;
- Do not stop all jobs when one fails.

Support Ubuntu 20.04 LTS

---

psydac/api/discretization.py
psydac/api/tests/test_api_2d_compatible_spaces.py
psydac/linalg/block.py

Improve `Equation.solve()`:
- In addition to `cg` (conjugate gradient = CG) solver, allow `pcg` (pre-conditioned CG) and `bicg` (bi-CG);
- Fix bug when 'info = True' argument is passed to function;
- Correctly apply non-homogeneous Dirichlet boundary conditions to vector quantities.
Further improvements:
- Fix bug in `BlockMatrix.tosparse()` when `scipy.sparse.bmat()` computes wrong shape because of too many empty blocks;
- Extend 2D Stokes unit tests (add non-homogeneous test, verify results with Scipy).

Improve solution of vector problems

---

psydac/api/fem.py
psydac/api/tests/test_assembly.py

Fixes #111:
Collect the free arguments in the correct order in `DiscreteBilinearForm.assemble()` and `DiscreteLinearForm.assemble()`. These methods can now handle free arguments containing both `Constant` and `FemField` objects.

Fix order of free arguments in assembly methods

---

psydac/api/ast/fem.py
psydac/api/tests/test_assembly.py

Fix bug in class `AST` from module `psydac.api.ast.fem`: in the generated code for the assembly of linear and bilinear forms, only the instructions for evaluating the last `FemField` argument were printed. We now print all the instructions required instead. This fixes #113.

Fix assembly code when multiple FemField objects are free arguments

---

psydac/api/ast/linalg.py
psydac/api/fem.py
psydac/linalg/stencil.py
psydac/linalg/tests/test_stencil_matrix.py
setup.py

To accelerate the dot product, we first generate pure Python code specific to the dimensions and the format of the  `StencilMatrix` object,  after that, we use one of the backends to accelerate the Python code.
This is an example of the generated code for a StencilMatrix with dimensions = `(16, 16, 7,  7)`.
```python
from pyccel.decorators import types
@types("real[:,:,:,:]", "real[:,:]", "real[:,:]")
def dot_product(mat, x, out):
from itertools import product
for i1,i2 in product(range(0, 16, 1),range(0, 16, 1)):
v = 0.0
for k1,k2 in product(range(0, 7, 1),range(0, 7, 1)):
v += mat[3 + i1,3 + i2,k1,k2]*x[i1 + k1,i2 + k2]
out[3 + i1,3 + i2] = v
```
however, in the parallel case, we pass the number of rows as an argument, where processes can have a different number of rows.
The previous …

Accelerate matrix-vector multiplication with backends

---

psydac/feec/global_projectors.py
psydac/linalg/block.py
psydac/linalg/tests/test_block.py

This PR introduces a new class `BlockDiagonalSolver`. The features are:
* Applies several `LinearSolvers` to parts of a `BlockVector`.
* Works as a `LinearSolver` on `BlockVectorSpace`s. (it also inherits from `LinearSolver`)
* Includes tests.
* Updates projector code to use `KroneckerLinearSolver` and the introduced `BlockDiagonalSolver`.

Add `BlockDiagonalSolver` for combining `LinearSolver`s

---

psydac/api/ast/evaluation.py
psydac/api/ast/expr.py
psydac/api/ast/glt.py
psydac/api/ast/linalg.py
psydac/api/ast/parser.py
psydac/api/ast/utilities.py

Move function `build_types_decorators` to Psydac:
- Copied from `pyccel.ast.utilities` (Pyccel version 0.10.1);
- Renamed as `build_pyccel_types_decorators`.

Add function `build_pyccel_types_decorators` to psydac.ast.utilities

---

psydac/api/ast/utilities.py
psydac/api/tests/test_assembly.py

Fix #123:
- Process dtype of `Constant` objects in function `build_pyccel_types_decorator`;
- Test assembly with `Constant` and `FemField` objects using multiple backends.

Accelerate expressions containing `Constant` objects with Pyccel

---

psydac/linalg/basic.py
psydac/linalg/tests/test_stencil_matrix.py
psydac/linalg/tests/test_stencil_vector.py

This PR updates the division operator to Python 3 (assuming that Python 2 support is obsolete/removed already),
i.e. it enables us to do e.g. `M /= a` where `M` is a `Matrix` or `Vector` object, and `a` is something that we can invert and have `M *= a` implemented, e.g. `a` could be a scalar. Note that we do not implement `__floordiv__` here (if that should be needed at all).
* `__div__` -> `__truediv__`, `__idiv__` -> `__itruediv__`
* Adds simple tests for `StencilMatrix` and `StencilVector` concerning some of their operators.

Fix `__div__` -> `__truediv__`

---

psydac/api/tests/test_api_feec_1d.py
psydac/api/tests/test_api_feec_3d.py
psydac/feec/derivatives.py
psydac/feec/tests/test_differentiation_matrices.py
psydac/linalg/block.py
psydac/linalg/kron.py

This PR adds a class `DirectionalDerivativeOperator` which can differentiate `StencilVector`s from a `StencilVectorSpace`, ideally associated to some `TensorFemSpace`. Its features are:
* Matrix-free computation (just one array subtraction, i.e. `np.subtract`; no additional temporary memory needed) of derivatives for a `TensorFemSpace` and its `StencilVectorSpace`.
* Inherits from `psydac.linalg.basic.Matrix`.
* Can be converted to a `KroneckerStencilMatrix` which in turn can be converted into a `StencilMatrix`. Also supports conversion to the COO format.
* Can also be transposed and negated.
Additionally, this PR features:
* Small clean-up of the `DiffOperator` subclasses.
* Includes tests; also fixed the seed for the existing differential operator tests.
* Some fixes for the tests to …

Add `DirectionalDerivativeOperator` for matrix-free derivative computation

---

psydac/linalg/iterative_solvers.py
psydac/linalg/tests/test_pcg.py

This PR slightly modifies the `psydac.linalg.iterative_solvers.pcg`, so that we may use a `LinearSolver` object or a callable function instead of a string, or simply input `None` as preconditioner. (note that as of now, this PR modifies as little as necessary)
* If we input no preconditioner (i.e. `pc is None`), the regular `cg` method is called.
* If a `LinearSolver` is used, it utilizes the `out` parameter of the `solve` method, i.e. we do not allocate a new vector for each round.
* If a callable function is used, the parameter format is as for the functions which are addressable as strings. I.e. we have `function(A, r)`, where we want to solve `As = r`. `s` is always re-allocated.
* The two string parameters `'jacobi', 'weighted_jacobi'` are kept for compatibility reasons with the …

Update PCG method to support `LinearSolver` and callable functions as input argument

---

psydac/api/discretization.py
psydac/api/fem.py
psydac/api/tests/test_quadorder.py
psydac/fem/tensor.py

This PR fixes a bug which could cause segmentation faults / out of bounds errors (depending on the backend used) when using the `quad_order` parameter with the `discretize` method.
* Discretization to a `TensorFEMSpace` now properly processes the `quad_order` parameter.
* (Bi)linear forms etc. need to have the same `quad_order` for now, as they use the underlying `TensorFEMSpace` quadrature grids. (allowing deviations here, e.g. by generating new quadrature grids on-demand may be done in a future PR) If we inserted a larger `quad_order` than there would be given to the space, we would get an out of bounds error (or segfault when compiling with pyccel; or just incorrect results), and if we chose a too small `quad_order` here, we would only use some quadrature points from the larger …

Propagate the `quad_order` parameter in the space discretization

---

psydac/linalg/direct_solvers.py
psydac/linalg/fft.py
psydac/linalg/kron.py
psydac/linalg/tests/test_fft.py
psydac/linalg/tests/test_kron_direct_solver.py

This PR adds some basic multi-dimensional FFT methods which work in a distributed environment (i.e. it enables us to compute `fftn`, `ifftn`, `dctn`, etc. in a distributed/parallel setting for `StencilVector`s).
* Implements FFT, DCT, DST, and all their inverse methods (for compatibility).
* Internally, it uses a `KroneckerLinearSolver` to do the FFT/DCT/DST in each direction. Currently, it uses `scipy.fft` without additional padding for the one-dimensional FFTs; the normalization and worker parameters are forwarded to the methods. (future optimization, like padding, FFTW support, slab distribution or support for `mpi4py_fft` etc. are subject of future PRs)
* To support all this, we also propagated the `StencilVectorSpace.dtype` to the datatype of the temporary arrays.
* Includes basic …

Add basic support for distributed multi-dimensional FFTs

---

psydac/api/tests/test_api_feec_1d.py
psydac/api/tests/test_api_feec_2d.py
psydac/fem/grid.py
psydac/fem/splines.py
psydac/fem/tensor.py
psydac/fem/tests/test_grid_decomposition.py
psydac/linalg/stencil.py

This PR fixes a bug in relation to the `FemAssemblyGrid` when `pad` does not equal `degree`. Previously, there seemed to be some discrepancies on multiple processes (except for the first one) at least on a periodic grid which caused a segmentation fault or an out of bounds error in the kernel, depending on if pyccel was used or not. Now, the spans are elevated on all processes, if `pad==degree+1`. (i.e. the padding parameter is used instead of the degree parameter) Henceforth, this PR does:
* Make DeRham work in parallel;
* Take the pad parameter directly from the `SplineSpace`;
* (sort of) fix `local_element_start` and `local_element_end` in the corner cases, where `end < degree`;
* Include small tests;
* Add parallel unit tests to files `test_api_feec_1d.py` and `test_api_feec_2d.py`, …

Fix distributed/parallel spline assembly when using DeRham complexes

---

psydac/api/equation.py
psydac/api/fem.py
psydac/api/tests/test_equation.py

- Correctly pass free arguments to lifting solver for non-homogeneous Dirichlet boundary conditions;
- Fix problem in `DiscreteSumForm.free_args`, which now returns a single tuple of variables instead of multiple tuples.

Handle free arguments (fields and constants) in essential BCs

---

psydac/api/ast/fem.py
psydac/api/ast/linalg.py
psydac/api/ast/nodes.py
psydac/api/ast/parser.py
psydac/api/basic.py
psydac/api/fem.py
psydac/api/grid.py
psydac/ddm/cart.py
psydac/linalg/block.py
psydac/mapping/discrete.py

- Simplify the generated code of the dot product when shift == 1
- Remove the MPI barrier from the ghost regions update
- Decouple the mapping space from the test space
- Multiply the test basis function by the quadrature weights
- Assemble only the necessary parts without the ghost regions in the parallel case

Make assembly algorithm and dot product faster

---

.github/workflows/continuous-integration.yml
requirements.txt
setup.py

Avoid runtime errors when loading pyccelized modules, caused by version mismatch between Numpy header used by Pyccel and installed Numpy library:
- Add Numba to requirements.txt in order to make sure that Pyccel and its dependencies are built against the same Numpy version (numba 0.55.0 requires numpy<1.22)
- Add Numba and Igakit to dependencies in setup.py

Fix installation process

---

examples/poisson_2d_mapping.py
psydac/fem/tensor.py
psydac/mapping/discrete.py

Make sure that the low-level example script `psydac/examples/poisson_2d_mapping.py` works with the latest version of Psydac:
- Use `CallableMapping` from `sympde.topology.callable_mapping` instead of `AnalyticalMapping` from `psydac.mapping.analytical` (which does not exist anymore)
- Use gallery of analytical mappings from `SymPDE`
- Use `Geometry` class from `psydac.cad.geometry` to read and write HDF5 geometry files
- Use new signature of mapping evaluation methods
- Bugfix in library: change (eta) to (*eta) when calling jac_mat and metric

Fix 2D Poisson example

---

.github/workflows/continuous-integration.yml
README.md
psydac/core/bsplines.py
psydac/core/bsplines_pyccel.py
psydac/core/tests/test_bsplines_pyccel.py

This PR aims at providing pyccelisable versions of the core functions in `bspline.py`. This consists of the file  `bsplines_pyccel.py` that is a transcription in pyccel-friendly python of `bsplines.py`. There is also a new test file that I used to make sure that those "new" functions yielded the correct results. This test file ought to be removed once the PR is ready.

Pycellisation of the functions in `bsplines.py`

---

.github/workflows/continuous-integration.yml
README.md
pyproject.toml
requirements.txt
requirements_extra.txt
setup.py

Igakit (not on PyPI) was just moved to GitHub, hence we are updating its URL in our `setup.py` file. This solves #206.
Because of the incompatibility between the Numpy build versions for Numba and Igakit, we now install Igakit without a pip isolated environment in order to use the same Numpy version that was previously installed by Numba. To this end we now list Igakit in a new file, `requirements_extra.txt`, which is dedicated to non-isolated builds.
In addition, we add the new file `pyproject.toml` in accordance to PEP 518.

Update igakit's URL. Build it w/ same Numpy version as Numba. Add pyproject.toml

---

psydac/fem/vector.py

Rename methods of `VectorFemField` class:
- `pushforward` -> `pushforward_field`
- `pushforward_grid`-> `pushforward_fields`
- `pushforward_regular_tensor_grid` -> `pushforward_fields_regular_tensor_grid`
Also apply some small corrections to the docstrings.

Correct names of pushforward functions in `VectorFemField`

---

examples/test_cg_perf.py
psydac/linalg/iterative_solvers.py
psydac/linalg/stencil.py

The `allreduce` function of mpi4py uses serialization which is slower than using `Allreduce` function that uses numpy arrays.
To illustrate that we run this [script](https://github.com/pyccel/psydac/blob/devel-allreduce/examples/test_cg_perf.py) using the old implementation vs the new implementation. 
```
using Comm.allreduce ...
number of procs :: 72
CG info      :: {'niter': 5003, 'success': True, 'res_norm': 8.064672720977876e-14}
Elapsed time :: 3.9431095123291016
using Comm.Allreduce ...
number of procs :: 72
CG info      :: {'niter': 5003, 'success': True, 'res_norm': 7.648109028693814e-14}
Elapsed time :: 1.0101466178894043
```

Use Comm.Allreduce instead of Comm.allreduce

---

psydac/core/bsplines.py
psydac/core/tests/test_bsplines_pyccel.py

In `fem/grid.py`, line 69-70, we reverse the order of arrays before giving them to `quadrature_grid`. Those view are not contiguous and thus need to be copied in a contiguous way before giving them to the pyccelised function in `bsplines_pyccel.py`. This wasn't done before and thus caused issue #223. 
To avoid further issues of the same kind, this PR replaced all of the `np.asarray` statements in `bsplines.py` into `np.ascontiguousarray`.

Enforce contiguity in `bsplines.py`

---

psydac/api/postprocessing.py
psydac/api/tests/test_postprocessing.py

This PR uncomments the tests using multi-patch geometry file in `psydac/api/tests/test_postprocessing.py` and changes the cross referencing of the space and fields file to use only the base name to avoid issues that could arise if the saving and post processing wasn't done in the same working directory.

Multipatch discrete geometry tests for `PostProcessManager`

---

.github/workflows/continuous-integration.yml
psydac/api/discretization.py
psydac/api/tests/test_2d_multipatch_mapping_maxwell.py
psydac/api/tests/test_2d_navier_stokes.py
psydac/api/tests/test_api_2d_compatible_spaces.py
psydac/api/tests/test_api_feec_3d.py
psydac/feec/global_projectors.py
psydac/feec/multipatch/examples/h1_source_pbms_conga_2d.py
psydac/feec/multipatch/examples/hcurl_source_pbms_conga_2d.py
psydac/feec/multipatch/plotting_utilities.py
psydac/fem/splines.py
psydac/linalg/__init__.py
psydac/linalg/block.py
psydac/linalg/stencil.py
psydac/linalg/tests/test_block.py
psydac/linalg/tests/test_stencil_matrix.py
psydac/linalg/tests/test_stencil_vector.py
psydac/linalg/topetsc.py
psydac/linalg/utilities.py
pytest.ini

- Add conversion methods called `topetsc` between Psydac data structures and PETSc data structures
- Add conversion method `petsc_to_psydac` between `Vec` data structure of PETSc and `Vector` of Psydac
- Add pytest marker `petsc` (currently used to skip any tests requiring PETSc)
TO DO: install PETSc and petsc4py on CI runner, and run all tests marked with `petsc`

PETSc interface

---

.github/workflows/continuous-integration.yml
README.md
requirements.txt
requirements_extra.txt

- Fix installation of `h5py` library by using `--no-build-isolation` flag and correct version of `setuptools`
- Fix macOS install by linking to correct version of `gfortran` (fixes #252)
- Also run tests with Python 3.10 on Ubuntu
- Use newer versions of actions: `checkout@v3` and `setup-python@v4`
- Update and improve README file

Fix installation and improve README

---

psydac/api/fem.py
psydac/api/tests/test_assembly.py

When assembling a discrete linear/bilinear form (or functional) which takes a `FemField` as parameter, make sure that the spline coefficients have up-to-date ghost regions. Failure to do so may yield wrong results.
Add a unit test showing how the error could show up. The test failed prior to the bug fix.

Update ghost regions before assembling a form

---

psydac/api/discretization.py
psydac/cad/geometry.py
psydac/ddm/cart.py
psydac/ddm/partition.py
psydac/ddm/tests/test_partition.py

Add new flag `mpi_dims_mask` to `discretize_domain`, which is successively passed to:
- `ddm.cart.DomainDecomposition`
- `ddm.partition.compute_dims`
- `ddm.partition.compute_dims_general`
Function `compute_dims_general` is the ones responsible to create the Cartesian grid of MPI processes. It receives `mpi_dims_mask` which is either `None` or a list of `bool`. In the latter case each element is set to `True` if the dimension is to be used in the domain decomposition (=default for each dimension). If `mpi_dim_mask[i] == False`, the i-th dimension is not decomposed.
Two unit tests for 2d and 3d have been added.

Do not decompose domain along user-specified dimensions

---

.github/workflows/continuous-integration.yml

Do not run tests on Linux with Python 3.8 and 3.9 on pull requests.
These jobs will be run after the merge into devel.
To see the changes at work please see [this PR](https://github.com/yguclu/psydac-docs-test/pull/1).

Reduce number of jobs run on pull requests

---

psydac/api/ast/parser.py
psydac/api/ast/utilities.py
psydac/api/tests/test_assembly.py

When collecting a common subexpression from a long expression in the AST, a temporary variable is created whose name is obtained from the `_name` attribute of the first SymPy object in a list. In certain unfortunate cases such an object does not have the `_name` attribute and an `AttributeError` is raised.
The problem is solved by cycling through each element in the aforementioned list, and extracting `_name` from the first object with such an attribute. This is done via the new `get_name` function. Fixes #327.

Do not access '_name' attribute of object with no name

---

psydac/linalg/solvers.py
psydac/linalg/tests/test_solvers.py

Add a `recycle` flag to the `__init__` of the subclasses of `InverseLinearOperator` defined in `linalg/solvers`.
By default `False`. If `True`, updates the initial guess `x0` to be a copy of the previous solution, without creating a temporary vector.
Previously, this feature could be implicitly used:
Given `A_solv`, an object of one of the solver classes defined in `linalg/solvers`, you could write
`x = A_solv.dot(b, out=A_solv._options["x0"])` instead of simply
`x = A_solv.dot(b)` or equivalently `x = A_solv @ b`.
However, this method has (at least) one major drawback:
**Application in a composition of linear operators**
Say you have to solve `Sx = b_n` for x at each type step of your simulation, where the right hand side `b_n` changes at each time step, and where S is a composition of …

Add `recycle` flag to linear solvers' constructors

---

psydac/feec/derivatives.py
psydac/feec/tests/test_commuting_projections.py
psydac/feec/tests/test_commuting_projections_dual.py
psydac/feec/tests/test_differentiation_matrices.py

Ensure the directional derivative is correctly converted to sparse matrix when we use one cell and periodic BC along a certain axis. In this case the spline space has dimension 1 and contains only constant functions, and the application of the directional derivative operator should always return zero.
Fixes #337.

Fix `DirectionalDerivativeOperator.tosparse` w/ 1 cell & periodic

---

psydac/linalg/solvers.py
psydac/linalg/tests/test_solvers.py

In the iterative linear solvers take `dtype` from the domain or the codomain of the linear operator to be "inverted". This avoids reading the `dtype` property of the linear operator, which may not be properly defined in some cases. Specifically, the classes `GMRES` and `MinimumResidual` were fixed.

Fix dtype in GMRES and MINRES

---

psydac/api/ast/evaluation.py
psydac/api/ast/expr.py
psydac/api/ast/glt.py
psydac/api/ast/linalg.py
psydac/api/ast/parser.py
psydac/api/ast/utilities.py
psydac/api/basic.py
psydac/pyccel/ast/core.py
psydac/pyccel/codegen/printing/pycode.py
pyproject.toml

Remove usage of `@types` decorators from the generated kernels. Use type annotations instead, as this allows using the future versions of Pyccel to accelerate our kernels. Fixes #342.
Main changes
--------------
* Create new AST node `AnnotatedArgument` in `psydac.pyccel.ast.core`, which contains a `name` (the original argument) and an `annotation` (a string specifying the type).
* Add method `_print_AnnotatedArgument` to `PythonCodePrinter` in `psydac.pyccel.codegen.printing.pycode`. This method just prints `f"{name} : {annotation}"`.
* Create function `build_pyccel_type_annotations` in `psydac.api.ast.utilities`, which takes a list of function arguments (currently of type `Variable`, `IndexedVariable`, or `Constant`) and returns a list of `AnnotatedArgument` objects.
* Make generated …

Use type annotations in generated code

---

psydac/api/ast/parser.py
pyproject.toml

Functions in printed code now are imported from `cmath` instead of `Numpy` in the case of a complex domain. This solves #313.
If the domain is real they are imported from `math` as before.
This change requires Pyccel version >= 1.9.2 which supports the cmath library.

Import functions from cmath when domain is complex

---

psydac/feec/tests/test_commuting_projections.py
psydac/feec/tests/test_commuting_projections_dual.py

- Add multiplicity to the parametrization of the unit tests in `test_commutativity_projections.py` and `test_commutativity_projections_dual.py`;
- Relax the tolerance of the tests in `test_commutativity_projections_dual.py` (alternatively, more quadrature points could be used).
Fixes #350.

Test commutativity of de Rham diagram with knot multiplicity > 1

---

psydac/linalg/basic.py

Maintain the original order of the addends in the method `simplify` of class `SumLinearOperator`. This is achieved by using `dict` (which preserves the insertion order as part of the language specification as of Python 3.7) in place of `set` (which does not keep an order). As a consequence of the deterministic ordering, every process in a parallel run now has the same identical addends. Earlier this was not always the case, which resulted in random errors.
A minimal reproducible example is not included because the bug appears to be system- and configuration-dependent.

 Fix parallel bug in `simplify` method of `SumLinearOperator`

---

.github/workflows/continuous-integration.yml

* Make sure `--oversubscribe` flag is used in MPI tests on macOS
* Create separate workflow step for MPI tests

Fix MPI parallel tests on macOS

---

.github/workflows/continuous-integration.yml
psydac/core/tests/test_bsplines_pyccel.py
pyproject.toml

- Use all available cores to run our unit tests.
- Distribute single-process tests across cores using the `xdist` plugin of Pytest.
- Fix random seed to make sure that all `xdist` workers see the same random parameters.
- Use Python 3.10 on macOS instead of 3.9

Speed up unit tests

---

.gitignore
psydac/api/settings.py
psydac/linalg/tests/test_stencil_matrix.py
pyproject.toml

- Give the flag `-mavx` to the GFortran compiler only if the processor's architecture is `x86_64`.
- Clean up the backends settings in `psydac.api.settings`.
- Update `.gitignore`.

Fix GFortran compiler flags on ARM processors

---

psydac/core/field_evaluation_kernels.py
psydac/linalg/kernels/axpy_kernels.py
psydac/linalg/kernels/inner_kernels.py
psydac/linalg/kernels/matvec_kernels.py
psydac/linalg/kernels/stencil2coo_kernels.py
psydac/linalg/kernels/transpose_kernels.py
psydac_accelerate.py
pyproject.toml

Use partial templates to generate the minimum possible number of functions.
Fixes #383.
- Use partial types in templates
- Require Pyccel version 1.11.2 or newer, as it contains a necessary bugfix
- Improve printing to terminal of script psydac_accelerate.py

Speed up Pyccelization of built-in kernels

---

examples/maxwell_2d_multi_patch.py

In `psydac/examples/`, the file `maxwell_2d_multi_patch.py` did not run because of this line
`equation_h.set_solver('pcg', pc='jacobi', tol=1e-8, info=True)`
Passing the string `'jacobi'` is no longer allowed since PR #360.
I copied the workaround found in `api/tests/test_2d_multipatch_mapping_maxwell.py`:
```python
equation_h.assemble()
jacobi_pc = equation_h.linear_system.lhs.diagonal(inverse=True)
equation_h.set_solver('pcg', pc=jacobi_pc, tol=1e-8, info=True)
```

Fix example file maxwell_2d_multi_patch.py

---

psydac/linalg/basic.py
psydac/linalg/block.py

Add the missing statement `return out` to the method `copy` of the class `BlockLinearOperator`. Also handle the corner case of `out=self`.

Fix bug in `copy` method of `BlockLinearOperator`

---

.github/workflows/continuous-integration.yml
README.md
psydac/api/tests/test_api_2d_compatible_spaces.py
psydac/linalg/tests/test_block.py
psydac/linalg/tests/test_stencil_matrix.py
psydac/linalg/tests/test_stencil_vector.py
psydac/linalg/topetsc.py
psydac/linalg/utilities.py
pyproject.toml

Fix the functions to cast Psydac format to PETSc format and back:
- Identify the correct installation procedure for PETSc and `petsc4py`;
- Make functions work on complex-valued vectors and matrices;
- Make functions work in the serial case (where `comm=None`);
- Add more extensive unit testing;
- Update unit test workflow;
- Update README file.
This allows the use of high-performance PETSc solvers:
- PETSc must be installed with the complex configuration (see the instructions in the README).
- `StencilVector`, `BlockVector`, `StencilMatrix` and `BlockLinearOperator` have a `topetsc()` method.
- The function `petsc_to_psydac` in `psydac.linalg.utilities.py` allows us to convert a `PETSc.Vec` object (for instance, the vector solution after solving a system with PETSc) back to Psydac …

Conversion to PETSc with complex

---

.github/workflows/documentation.yml
docs/source/conf.py
docs/source/index.rst
docs/source/maintenance.rst
docs_requirements.txt
psydac/linalg/basic.py
pyproject.toml

**The first of potentially weekly(?) PRs improving Psydac's docstrings - any contribution is welcome @pyccel/psydac-dev !**
Files updated so far in this PR:
- `linalg.basic`
**Note:** I have started using :math:\`[insert standard latex code]\` in the docstrings of `linalg.basic` inspired by STRUPHY. Do we want to use this math-mode everywhere?
**To locally view your changes:**
- If not already done, now is a good time to create a venv
- If not already done: (let me know if these are not enough)
- `sudo apt install graphviz` (Linux) or `brew install graphviz` (macOS)
- `python -m pip install -r docs_requirements.txt`
- Go to `psydac/docs/`
- Execute `make html` *)
- Open the documentation on your browser with `open build/html/index.html`
*) While not necessary, instead of `make html` only, …

Improve developers' documentation

---

psydac/feec/pushforward.py
psydac/feec/tests/test_pushforward.py
psydac/linalg/tests/test_stencil_matrix.py

there was a small bug in the Pushforward function, when no `grid_local` was passed for a mapping of `Mapping` type
I also added a unit test

Fix `None` value in `Pushforward`

---

psydac/core/bsplines.py
psydac/core/bsplines_kernels.py
psydac/core/tests/test_bsplines_kernel.py

In `cell_index_p` we look for cells containing points. If a point is outside the domain exactly at `tol` distance from the bounds, then the search loop will be stuck in infinite recursion. One way to fix this is to lower the tolerance when checking if the points are within the domain (before actually entering the loop).
**Edit (21.03.2024):**
in this PR I also fix the `status` value returned by the cell search in `cell_index_p`, so that it is:
- 0 if all points are in domain
- -1 if some points are outside domain as expected by calling `cell_index` (was 1 before)
- -2 if search can't decide
in the third case the previous code was actually caught in an infinite loop. To avoid this behaviour I added a max number of iterations in `cell_index_p`
(and a unit test)

Fix several errors in `cell_index_p`

---

psydac/core/field_evaluation_kernels.py
psydac/core/tests/test_field_evaluation_kernel.py
psydac/fem/tensor.py

The ``eval_fields`` method of class `TensorFemSpace` raises a ``NotImplementedError`` when called to evaluate fields in 1D. To fix this, the missing 1D kernels have been added, and they are now called when needed.
List of changes
--------------
- Add kernel functions ``eval_fields_1d_no_weights``, ``eval_fields_1d_irregular_no_weights``, ``eval_fields_1d_weighted``, and ``eval_fields_1d_irregular_weighted`` to ``psydac/core/field_evaluation_kernels.py``. 
- Modify functions ``eval_fields_irregular_tensor_grid`` and ``eval_fields_regular_tensor_grid`` in ``psydac/fem/tensor.py`` to call these kernel functions in the case of 1D fields.
- Add several 1D tests to ``test_regular_evaluations`` in ``psydac/core/tests/test_field_evaluation_kernel.py``.
Note
-------
An evaluation kernel for the L2 …

Add 1D field evaluation kernels

---

.github/workflows/continuous-integration.yml
README.md

On Ubuntu 22.04, `h5pcc -showconfig` gives the wrong installation point required by `h5py`:
```sh
SUMMARY OF THE HDF5 CONFIGURATION
=================================
General Information:
-------------------
HDF5 Version: 1.10.7
Configured on: Wed, 08 Dec 2021 23:33:27 +0000
Configured by: Debian
Host system: x86_64-pc-linux-gnu
Uname information: Debian
Byte sex: little-endian
Installation point: /usr
Flavor name: openmpi
```
`pip3 install h5py` will look for `libhdf5.so` which is at `/usr/lib/x86_64-linux-gnu/hdf5/openmpi`, not `/usr`. On Ubuntu/Debian one could directly extract `HDF5_DIR` with the command
```sh
export HDF5_DIR=$(dpkg -L libhdf5-openmpi-dev | grep libhdf5.so | xargs dirname)
```
I wonder if we should still suggest `h5pcc -showconfig` which doesn't really work and may …

Provide alternative shell command for discovering HDF5_DIR

---

psydac/linalg/tests/test_block.py
psydac/linalg/tests/test_stencil_vector.py
psydac/linalg/utilities.py

The function `array_to_psydac`:
- was not working in parallel
- was not tested in parallel
- was not general enough
This PR fixes it and rewrites it in a recursive way, so that it also works in more general cases as for example:
- A `BlockVectorSpace` of a `BlockVectorSpace` and a `StencilVectorSpace`
- A `BlockVectorSpace` of a `BlockVectorSpace`  of a `BlockVectorSpace`

Improve function `array_to_psydac`

---

.github/workflows/continuous-integration.yml
setup.py

Solves first TODO item in #406.  Summary of changes:
* Removed `finalize_options()` since this method does not differ from its [base class implementation](https://github.com/pypa/setuptools/blob/b3fc00fe1b242714029f46f03cafaaf324ae380d/setuptools/command/build_py.py#L38-L44), therefore making the override unnecessary.
* For `run()`, it's sufficient to call the [base class `run()`](https://github.com/pypa/setuptools/blob/b3fc00fe1b242714029f46f03cafaaf324ae380d/setuptools/command/build_py.py#L57) and then add the custom `pyccel` commands.
* `sub_run()` should throw an error instead of failing silently (`check=True`).
* Formatted code to conform with `Pylint` and `PEP8` checks

Remove deprecated distutils (Python >=3.12)

---

psydac/linalg/basic.py

The `__neg__` function in class `LinearOperator` uses the `_domain` and `_codomain` attributes, which is wrong since these may not be defined. It should use the exposed (interface) properties `domain` and `codomain` instead.

Use public properties `domain` & `codomain` in `LinearOperator.__neg__`

---

psydac/feec/tests/test_commuting_projections.py

Changed `IdentityLinearOperator` to `IdentityOperator` and `e0 @ e0` to `e0.dot(e0)`

Fixes in `test_3d_commuting_pro_1`

---

.github/workflows/continuous-integration.yml
README.md

current README mentions possibility of selecting C as pyccel backend, but not always possible, see issue #431

Mention C support in near future in README.md

---

.github/workflows/continuous-integration.yml

Update `apt` index files with `apt-get update` to avoid download error in CI workflow.

Circumvent `apt-get` download error

---

README.md

Clarify in the `README.md` file that, although the C backend may be selected for accelerating the kernel files with Pyccel, this is not fully working yet. Hence the Fortran backend (which is the default) is the only one available. A future version of Pyccel will certainly provide a C backend as capable as the Fortran one. See issue #431.

Mention C support in near future in README

---

psydac/linalg/kernels/stencil2coo_kernels.py
psydac/linalg/tests/test_stencil_matrix.py

Fix the indexing in all kernels in `stencil2coo_kernels.py` so that the method `toarray` works for `StencilMatrix` objects in 1D/2D/3D with `shift` larger than 1.
The unit tests for `toarray` in `test_stencil_matrix.py` have been parametrized to run with `shift` values of 1 and 2.

Update `stencil2coo` kernels for shifts > 1

---

.github/workflows/continuous-integration.yml
README.md

From @yguclu:
> If people have a cached version of the h5py library which was compiled using NumPy < 2.0 and try to install Psydac in a clean Python environment, they end up with a broken version. This is because the cached version of h5py tries to call C functions from NumPy 2.0 which are not ABI compatible.
Adding [`--no-cache-dir`](https://stackoverflow.com/questions/45594707/what-is-pips-no-cache-dir-good-for) to `pip` guarantees that `h5py` is always [built during installation](https://docs.h5py.org/en/stable/build.html#custom-installation). Re-using a prebuilt `h5py` (*i.e.* cached `h5py`) could become an issue stale when `h5py` dependencies upgrade.

Avoid installing h5py from cache

---

psydac/linalg/basic.py

Allow the creation of a `MatrixFreeLinearOperator` object with a dot function that takes multiple keyword arguments, as for instance function parameters.

Allow keyword parameters in the dot method of `MatrixFreeLinearOperator`

---

psydac/linalg/basic.py
psydac/linalg/solvers.py
psydac/linalg/tests/test_linalg.py

- Make `ScaledLinearOperator` work with a complex scalar;
- Take real part of `r.dot(r)` to avoid complex warning in `sqrt`;
- Add unit test.

Small fixes for operators with complex

---

psydac/core/bsplines.py
psydac/fem/splines.py

Previously, in the case when `self.greville.size == 1`, `collocation_matrix` would return an empty matrix.
Now, if the grid has a single Greville point, the collocation matrix is simplified to a 1x1 matrix with a value of 1.

Fix Greville point collocation matrix for single grid point case

---

psydac/ddm/blocking_data_exchanger.py
psydac/ddm/cart.py
psydac/ddm/nonblocking_data_exchanger.py
requirements.txt

Closes #420.
Fix usage of function `Translate_ranks` which had non-backward-compatible changes in mpi4py version 4.0: https://mpi4py.readthedocs.io/en/stable/changes.html.

Enable mpi4py 4.0

---

psydac/api/settings.py

Currently, psydac can not be used on Apple M4 computers since the `PSYDAC_BACKEND_GPYCCEL['flags']` is not set correctly.
This change sets the flag for `Apple MX` to `apple-mx`, which I think is a good enough guess for now. I tested it on a Mac with an Apple M4 chip.

Fix PSYDAC_BACKEND_GPYCCEL flags on latest Apple silicon

---

psydac/feec/global_projectors.py
psydac/feec/multipatch/examples/timedomain_maxwell.py
psydac/linalg/basic.py

Changes:
* Use raw strings for docstrings with LaTeX to avoid UTF8 syntax warnings on escape sequences;
* Use CSC matrices to avoid SciPy sparse solver warning.
We do not address the NumPy warnings which arise in our MPI unit tests (see #353).

Resolve warnings in sequential unit tests

---

psydac/api/ast/linalg.py
psydac/api/tests/test_assembly.py
psydac/feec/tests/test_commuting_projections.py
psydac/feec/tests/test_global_projectors.py
psydac/linalg/basic.py
psydac/linalg/block.py
psydac/linalg/solvers.py
psydac/linalg/stencil.py
psydac/linalg/tests/test_block.py
psydac/linalg/tests/test_linalg.py
psydac/linalg/tests/test_stencil_interface_matrix.py
psydac/linalg/tests/test_stencil_vector.py
psydac/polar/dense.py

Main changes
--------------
* Rename the method `dot` of the base class `VectorSpace` as `inner`, and make it an abstract method (which must be implemented by the subclasses).
* Rename the method `dot` of the base class `Vector` as `inner`. This is a concrete method which calls `self.space.inner` and does not need to be overridden by the subclasses.
* Add `inner` methods to the classes `StencilVector`, `BlockVectorSpace`, and `DenseVectorSpace`. These methods override the abstract method of the base class as required, and are derived from the former functions `Stencil.dot`, `BlockVector.dot`, and `DenseVector.dot`, which have been removed (see next point).
* Remove the property `dtype` and the method `dot` (now `inner`) from the classes `StencilVector`, `BlockVector`, and `DenseVector`, …

Rename `dot` as `inner` in `Vector`, `VectorSpace`, and subclasses

---

psydac/linalg/basic.py
psydac/linalg/tests/test_linalg.py
psydac/linalg/tests/test_matrix_free.py

Implement `M.dot(u).inner(v)`, or `(M @ u).inner(v)`, without creating a temporary vector. The result of the dot product is written to a local work vector stored in the `LinearOperator` object. This work vector is then used to compute the inner product with the vector `v`. The subclasses do not need to override this method, unless a more efficient implementation which avoids writing to the work vector altogether (reducing memory pressure) is needed.
A unit test is added: function `test_dot_inner` in file psydac/linalg/tests/test_linalg.py.
Additionally, the helper function `get_StencilVectorSpace` defined in psydac/linalg/tests/test_linalg.py (only used in the same file and in test_matrix_free.py) has a new signature and now works in any number of dimensions.
Fixes #491.

Add a `dot_inner` concrete method to the base class `LinearOperator`

---

psydac/api/fem.py

Always use the maximum padding between test and trial spaces in `allocate_matrices` in `DiscreteBilinearForm`. (Earlier this was not done in the case of scalar spaces.) Fixes #504.

Fix bug in `allocate_matrices` in `DiscreteBilinearForm`
